-- Portable between PostgreSQL (runtime) and H2 in PostgreSQL mode (tests).

CREATE TABLE conversations (
    id              VARCHAR(64)  NOT NULL PRIMARY KEY,
    version         INT          NOT NULL DEFAULT 0,
    phone_number    VARCHAR(20)  NOT NULL,
    customer_id     VARCHAR(64),
    campaign_id     VARCHAR(64),
    stage           VARCHAR(32)  NOT NULL,
    stage_data      VARCHAR(2000) NOT NULL,
    is_open         BOOLEAN      NOT NULL,
    last_inbound_at TIMESTAMP(6) WITH TIME ZONE,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_conversations_phone_open ON conversations (phone_number, is_open);
CREATE INDEX idx_conversations_customer ON conversations (customer_id);

CREATE TABLE messages (
    id              VARCHAR(64)  NOT NULL PRIMARY KEY,
    version         INT          NOT NULL DEFAULT 0,
    conversation_id VARCHAR(64)  NOT NULL REFERENCES conversations (id),
    direction       VARCHAR(8)   NOT NULL,
    wamid           VARCHAR(128) UNIQUE,
    content_type    VARCHAR(32)  NOT NULL,
    content         TEXT         NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    failure_reason  VARCHAR(1000),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_messages_conversation ON messages (conversation_id, created_at);

CREATE TABLE campaigns (
    id                  VARCHAR(64)  NOT NULL PRIMARY KEY,
    version             INT          NOT NULL DEFAULT 0,
    name                VARCHAR(255) NOT NULL,
    template_name       VARCHAR(512) NOT NULL,
    template_language   VARCHAR(16)  NOT NULL,
    template_parameters TEXT         NOT NULL,
    status              VARCHAR(16)  NOT NULL,
    sent                INT          NOT NULL DEFAULT 0,
    failed              INT          NOT NULL DEFAULT 0,
    skipped             INT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    started_at          TIMESTAMP(6) WITH TIME ZONE,
    finished_at         TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE campaign_recipients (
    campaign_id VARCHAR(64) NOT NULL REFERENCES campaigns (id),
    customer_id VARCHAR(64) NOT NULL,
    position    INT         NOT NULL,
    PRIMARY KEY (campaign_id, customer_id)
);

CREATE TABLE events (
    event_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processed      BOOLEAN      NOT NULL DEFAULT FALSE,
    attempts       INT          NOT NULL DEFAULT 0,
    last_error     VARCHAR(1000),
    aggregate_type VARCHAR(32)  NOT NULL,
    aggregate_id   VARCHAR(64)  NOT NULL,
    event_type     VARCHAR(255) NOT NULL,
    event_date     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    event_data     TEXT         NOT NULL
);

CREATE INDEX idx_events_pending ON events (processed, event_id);
CREATE INDEX idx_events_aggregate ON events (aggregate_id);
